### ISSUE TITLE
Printed SDL returned by the service capabilities query should not return schema element

### ISSUE THREAD

**Issue by mcohen75** [apollographql/federation-jvm#2] opened 2019-06-13 20:18 UTC
The Federation Specification appears to indicate that the printed SDL returned by the `_service` query should not return the root schema element with root operation definitions.

https://www.apollographql.com/docs/apollo-server/federation/federation-spec/#fetch-service-capabilities

The current implementation adds the `schema` node with root operations defined. The gateway fails to create a merged schema with the following error:
```
(node:63550) UnhandledPromiseRejectionWarning: GraphQLSchemaValidationError: Query root type must be provided.
    at ApolloGateway.createSchema (.../node_modules/@apollo/gateway/dist/index.js:92:19)
    at ApolloGateway.<anonymous> (.../node_modules/@apollo/gateway/dist/index.js:81:22)
    at Generator.next (<anonymous>)
    at fulfilled (.../node_modules/@apollo/gateway/dist/index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

apollo/gateway: 0.6.5
apollo-server: 2.6.2

**Comment by pcarrier** [comment] 2019-07-08 01:29
As discussed in https://github.com/apollographql/federation-jvm/pull/3 it should be fine to include those fields. @trevor-scheer could you suggest a way to troubleshoot this further?

**Comment by trevor-scheer** [comment] 2019-07-08 04:09
@mcohen75 I don't think this error necessarily implies an issue with including the schema definition node. The composition work can actually accommodate SDL with or without the schema definition.

The error _does_ seem to indicate that there's no `Query` type at all, which could be problematic, or an edge case that we're not handling correctly.

In order for us to identify the issue, can you provide a reproduction? The SDL returned by each federated service via `query { _service { sdl } }` should be sufficient for us to reproduce in a test.

**Comment by yuhanz** [comment] 2019-08-07 17:04
I had a similar issue. `_query { _service { sdl } }` on federation-jvm gives ```
{
  "errors": [],
  "data": {
    "_service": {
      "sdl": "schema {\n  query: Query\n}\n\ntype Query {\n  me: User\n}\n\ntype User @key(fields : \"id\") {\n  id: ID!\n  name: String\n  username: String\n}\n"
    }
  },
  "extensions": null,
  "dataPresent": true
}``` 

where ApolloGateway is expecting a different format with the same _schema.grapql_ file:
```
{
  "data": {
    "_service": {
      "sdl": "extend type Query {\n  me: User\n}\n\ntype User @key(fields: \"id\") {\n  id: ID!\n  name: String\n  username: String\n}\n"
    }
  }
}
```
https://github.com/apollographql/federation-demo/blob/master/gateway.js#L14

Notice that federation-jvm doesn't have the *extend* keyword, besides including extra element for *schema*.

**Comment by yuhanz** [comment] 2019-08-07 21:02
Additionally, ApolloGateway doesn't like the empty Array in "errors".  ApolloGateway considers this as not having a schema:
```
{
  "errors": [],
  "data": {
    "_service": {
      "sdl": "extend type Query {\n  me: User\n}\n\ntype User @key(fields: \"id\") {\n  id: ID!\n  name: String\n  username: String\n}\n"
    }
  }
}
```

If the empty errors array is removed, and apply patch to below, ApolloGateway will recognize the service:
```
final String modified = sdl.replace("schema {\n  query: Query\n}\n\n", "");
_service.put("sdl", modified);
```

ApolloGateway tolerates the following difference:
- "fields :" as for "fields:"

**Comment by trevor-scheer** [comment] 2019-08-09 23:52
@yuhanz, can you please open separate issues for these? They are important but unrelated to the issue at hand. I'm going to close this, since returning a schema node in SDL is explicitly permitted by `@apollo/gateway`.

**Closed by trevor-scheer** 2019-08-09 23:52 UTC

**Comment by yuhanz** [comment] 2019-08-15 00:12
ok
