### ISSUE TITLE
_Entity type resolver and _entities data fetcher required for simple reference of external type

### ISSUE THREAD

**Issue by mbpreble** [apollographql/federation-jvm#150] opened 2022-03-30 16:17 UTC
I have a `graphql-java` API where I am trying to reference a type defined in another API under the same Federated umbrella. The referenced type is already available as an entity in the other API. In order to avoid declaring the full type myself (which will result in conflicts if it diverges from a type definition which I do not control), I am extending the type using the `@extends` directive as `graphql-java` will not permit the use of the `extend` keyword when building my runtime schema unless the base type has been declared as well.

The reference material I am following is available [here](https://www.apollographql.com/docs/federation/entities/#referencing-entities).

The minimal schema to support this (in my API) appears to be:
```
type MyType {
  externalData: ExternalType
}


type ExternalType @key(fields: "primaryKey") @extends {
  primaryKey: ID @external
}
```

In this case, `SchemaTransformer` finds the `@key` directive, thinks I am declaring a new `ExternalType` entity, and throws a `SchemaProblem` since I haven't added any runtime support.

As far as I know, in this very minimal case where I am only referencing an external type but not extending it in any way, I do not actually need any runtime support in the `_entities` query for `ExternalType`.

Overall this produces some slight friction in this use case as it seems like I need to supply a fake implementation of `_entities` which as far as I know won't actually be used at runtime (since the schema is so simple) but prevents creation of my federated schema.

Edit: This looks like it was also reported in #70. I am currently on version 0.9.0.

**Comment by martinbonnin** [comment] 2022-03-30 16:51
I think it's fair to filter out types that have both `@key` and `@extends` directive and not add `_entities` if there's none. I'll add that to the next 2.0 alpha

**Comment by mbpreble** [comment] 2022-03-30 17:08
Although it is probably (?) correct to have the enforcement for any actual extension of an external type as you're asking to have representations piped down and enhanced. Might be somewhat of a fiddly exercise to only skip cases that definitely don't need an `_entities` implementation.

**Comment by martinbonnin** [comment] 2022-03-30 20:43
Mmm I see... Damn that's a tough one. I guess "skip the extended type that only have `@external` fields"... But that somehow contradicts https://www.apollographql.com/docs/federation/federation-spec/#resolve-requests-for-entities that explicitly requires adding the extended types to the `_Entity` union.

**Comment by martinbonnin** [comment] 2022-03-31 15:47
Looking a bit more at this, I think the API is exposing the wrong level of abstraction. The caller shouldn't have to specify a `DataFetcher` for `_entities` but more something that takes a representation and returns the corresponding object. Something like

```kotlin
Federation.transform(sdl)
      .type("Product") { representation ->
        allProducts.firstOrNull { it.id == representation["id"] }
      }
      .type("User") { representation -> 
         // ...
      }
``` 

This would also map better with the [`subgraph-js`](https://github.com/apollographql/federation/blob/853bc8fa2d478dfd768581d4f351e467c4401ca3/subgraph-js/README.md#L31) API.

**Comment by dariuszkuc** [comment] 2023-01-06 19:57
`@external` / `external type` information is no longer needed in Federation v2. As mentioned above this is a duplicate of #70. Copy of my comment from that issue below.

>This was addressed in Federation v2 -> if you just need to reference entity now you can specify `resolvable: false` on the `@key` directive. This will ensure that the router/gateway will not attempt to resolve the type in the given subgraph and always make federated call.
>
>I've updated the logic in https://github.com/apollographql/federation-jvm/pull/285 to also auto populate `_Entity` union type resolver with a fake one (that throws runtime exception if invoked -> it should never be invoked, if for some reason it is, e.g. due to local testing, your provided resolver takes precedence) and no longer require _entities resolver if all entities are non-resolvable.

**Closed as completed by dariuszkuc** 2023-01-06 19:57 UTC
